using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace MirzaCryptoHelpers.AsymmetricCryptos
{
    /// <summary>
    /// This class performs Encryption and Decryption using RSA Algorithm (2048).
    /// </summary>
    public sealed class RsaCrypto : IAsymmetricCryptography
    {
        /// <summary>
        /// To encrypt/decrypt data, it must be called first to generate both keys
        /// and used to perform the operations.
        /// </summary>
        /// <returns>SessionsKeys. Returns null if GenerateKeys fails.</returns>
        public SessionKeys GenerateKeys()
        {
            SessionKeys sessionKeys = new SessionKeys();
            try
            {
                using (RSACryptoServiceProvider rsa = new RSACryptoServiceProvider(2048)
                {
                    PersistKeyInCsp = false
                })
                {
                    sessionKeys.PrivateKeyXml = rsa.ToXmlString(true);
                    sessionKeys.PublicKeyXml = rsa.ToXmlString(false);
                }
            }
            catch { sessionKeys = null; }
            return sessionKeys;
        }

        
        /// <summary>
        /// Encrypt the data using public key generated by GenerateKeys() method.
        /// </summary>
        /// <param name="data">Data to encrypt in bytes.</param>
        /// <param name="publicKeyXml">Public key in xml format.</param>
        /// <returns>Encrypted data in bytes.</returns>
        /// <exception cref="ArgumentNullException">'data' is null</exception>
        /// <exception cref="ArgumentNullException">'publicKeyXml' is null/empty.</exception>
        public byte[] Encrypt(byte[] data, string publicKeyXml)
        {
            byte[] cipher = null;
            using (RSACryptoServiceProvider rsa = new RSACryptoServiceProvider(2048)
            {
                PersistKeyInCsp = false
            })
            {
                try
                {

                    rsa.FromXmlString(publicKeyXml);
                    cipher = rsa.Encrypt(data, true);
                }
                catch { cipher = null; }
            }
           
            return cipher;
        }

        
        /// <summary>
        /// Decrypt the data using private key generated by GenerateKeys() method.
        /// PrivateKey must be generated along with PublicKey.
        /// </summary>
        /// <param name="data">Data to decrypt in bytes.</param>
        /// <param name="privateKeyXml">Private key in xml format.</param>
        /// <returns>Decrypted data in xml format.</returns>
        /// <exception cref="ArgumentNullException">'data' is null</exception>
        /// <exception cref="ArgumentNullException">'privateKeyXml' is null/empty.</exception>
        public byte[] Decrypt(byte[] data, string privateKeyXml)
        {
            byte[] plain = null;
            using (RSACryptoServiceProvider rsa = new RSACryptoServiceProvider(2048)
            {
                PersistKeyInCsp = false
            })
            {
                try
                {
                    rsa.FromXmlString(privateKeyXml);
                    plain = rsa.Decrypt(data, true);
                }
                catch { plain = null; }
            }
            return plain;
        }


    }
}
